name: learn-github-actions

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [10.x, 12.x, 14.x]

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Build Project
        run: npm run build --if-present
      -
        name: Setup ENV file
        run: cp .env.example .env
      -
        name: Run tests
        run: npm test
      -
        name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest, ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ steps.build.outputs.version_tags }}