name: learn-github-actions

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [10.x, 12.x, 14.x]

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Build Project
        run: npm run build --if-present
      -
        name: Setup ENV file
        run: cp .env.example .env
      -
        name: Run tests
        run: npm test
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Publish to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rogerarce/todo-api:latest, rogerarce/todo-api:${{ github.run_number }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      -
        name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Todo-api
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ job.status }}
