# Development Workflow
name: learn-github-actions

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Build Project
        run: npm run build --if-present
      -
        name: Setup ENV file
        run: cp .env.example .env
      -
        name: Run tests
        run: npm test
      -
        name: Caching # cached build can be reused if need by 1 of jobs
        uses: actions/cache@v2
        id: build-cache
        with:
          path: ./build
          key: ${{ github.sha }}
      -
        name: Slack Notification
        if: ${{ always() }} # executes step if job fails
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Todo-api
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ job.status }}
          SLACK_ICON: https://raw.githubusercontent.com/rogerarce/files/main/slackbot7.png